### ISSUE TITLE
It doesn't work with PHP 7

### ISSUE THREAD

**Issue by tomekpolska** [marcortola/food-data-central#2]
I run `composer require marcortola/food-data-central`

and created my on file run.php like this:

```
<?php

require_once 'vendor/autoload.php';

$foodDataCentralClient = FoodDataCentralClient::create('MY_API');

// Find food by FDC ID.
$foodItem = $foodDataCentralClient->food()->food(781125);

// Find food nutrients. See the FoodItem interface for more nutrient finders.
$calcium = $foodDataCentralClient->food()->food(781125)->getCalcium();


 ?>
```
Command line execution of the file failed due to following error:

`PHP Fatal error:  Uncaught Error: Class 'FoodDataCentralClient' not found in /home/tomek/Dokumenty/food_data/run.php:5
Stack trace:
#0 {main}
  thrown in /home/tomek/Dokumenty/food_data/run.php on line 5`

Here is my php:
`
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
`

Please help me to have this working. You did a great job with the API client anyway!

**Comment by marcortola** [comment]
You should import the class before using it:
```use MarcOrtola\FoodDataCentral\FoodDataCentralClient;```

**Comment by tomekpolska** [comment]
Thanks, my mistake, you're right. But there is another error:
```

PHP Fatal error:  Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
 - Puli Factory is not available
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Http\Discovery\Strategy\CommonClassesStrategy::symfonyPsr18Instantiate, GuzzleHttp\Client, Http\Discovery\Strategy\CommonClassesStrategy::buzzInstantiate.
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: .

 in /home/tomek/Dokumenty/food_data/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /home/tomek/Dokumenty/food_data/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\Exception\DiscoveryFailedException::create()
#1 /home/tomek/Dokumenty/food_data/vendor/php-http/discovery/src/Psr18ClientDiscovery.php(25): Http in /home/tomek/Dokumenty/food_data/vendor/php-http/discovery/src/Psr18ClientDiscovery.php on line 27

```

And the script:
```

<?php

require_once 'vendor/autoload.php';

use MarcOrtola\FoodDataCentral\FoodDataCentralClient;

$foodDataCentralClient = FoodDataCentralClient::create('MY_API');

// Find food by FDC ID.
$foodItem = $foodDataCentralClient->food()->food(781125);

// Find food nutrients. See the FoodItem interface for more nutrient finders.
$calcium = $foodDataCentralClient->food()->food(781125)->getCalcium();


 ?>

```

**Comment by marcortola** [comment]
This wrapper doesn't bundle the HTTP client so you are free to use your preferred one. You can inject it in the FoodDataCentralClient constructor or let the wrapper discover it. If you don't know what I am talking about, the fast solution is to require these packages:
```composer require php-http/curl-client nyholm/psr7 php-http/message```

It's not a problem with the wrapper itself. I thought it would be clear enough when reading the code, but maybe we should add some hints in the README.

**Comment by tomekpolska** [comment]
It wasn't so clear to me. Thanks for the help. It works now! Some hints would be appreciate.
